"""Upgrade genuine v89 output generated by starting main a917df5."""
from pathlib import Path
import tempfile
import unittest

import remote_access


FIXTURES = Path(__file__).parent / "fixtures" / "legacy-patches"


class ControllerV89UpgradeTests(unittest.TestCase):
    def test_genuine_v89_upgrade_preserves_upstream_backup_and_is_idempotent(self):
        original = (FIXTURES / "controller-upstream.txt").read_text()
        previous = (FIXTURES / "controller-v89.txt").read_text()
        self.assertIn(remote_access.LEGACY_COMPAT_MARKER_V89, previous)
        self.assertFalse(remote_access.legacy_controller_patch_current(previous))
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "remote_controller.py"
            backup = path.with_name(path.name + ".linux-rdaccess-backup")
            path.write_text(previous)
            backup.write_text(original)
            self.assertTrue(remote_access.patch_legacy_orca_remote_controller(path))
            current = path.read_text()
            self.assertTrue(remote_access.legacy_controller_patch_current(current))
            self.assertEqual(backup.read_text(), original)
            self.assertEqual(path.stat().st_mode & 0o777, 0o600)
            self.assertEqual(backup.stat().st_mode & 0o777, 0o600)
            self.assertFalse(remote_access.patch_legacy_orca_remote_controller(path))
            self.assertEqual(path.read_text(), current)

    def test_v90_through_v93_markers_upgrade_to_v94_from_original_backup(self):
        original = (FIXTURES / "controller-upstream.txt").read_text()
        for marker in (
            remote_access.LEGACY_COMPAT_MARKER_V90,
            remote_access.LEGACY_COMPAT_MARKER_V91,
            remote_access.LEGACY_COMPAT_MARKER_V92,
            remote_access.LEGACY_COMPAT_MARKER_V93,
        ):
            with self.subTest(marker=marker), tempfile.TemporaryDirectory() as directory:
                path = Path(directory) / "remote_controller.py"
                backup = path.with_name(path.name + ".linux-rdaccess-backup")
                path.write_text(original)
                self.assertTrue(remote_access.patch_legacy_orca_remote_controller(path))
                current = path.read_text()
                previous = current.replace(
                    remote_access.LEGACY_COMPAT_MARKER,
                    marker,
                )
                path.write_text(previous)
                self.assertFalse(remote_access.legacy_controller_patch_current(previous))
                self.assertEqual(backup.read_text(), original)
                self.assertTrue(remote_access.patch_legacy_orca_remote_controller(path))
                upgraded = path.read_text()
                self.assertIn(remote_access.LEGACY_COMPAT_MARKER, upgraded)
                self.assertNotIn(marker, upgraded)
                self.assertTrue(remote_access.legacy_controller_patch_current(upgraded))
                self.assertEqual(backup.read_text(), original)

    def test_genuine_v89_without_original_backup_is_preserved_and_rejected(self):
        previous = (FIXTURES / "controller-v89.txt").read_text()
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "remote_controller.py"
            path.write_text(previous)
            with self.assertRaisesRegex(ValueError, "backup is missing"):
                remote_access.patch_legacy_orca_remote_controller(path)
            self.assertEqual(path.read_text(), previous)


if __name__ == "__main__":
    unittest.main()
